CREATE TABLE "acquisition_funnel_benchmarks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"funnel_key" text NOT NULL,
	"benchmark_key" text NOT NULL,
	"sector" "prospection_sector",
	"value" real NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "acquisition_funnel_benchmarks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "acquisition_funnels" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"funnel_key" text NOT NULL,
	"label" text NOT NULL,
	"description" text NOT NULL,
	"steps" jsonb NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "acquisition_funnels_funnel_key_unique" UNIQUE("funnel_key")
);
--> statement-breakpoint
ALTER TABLE "acquisition_funnels" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "monthly_metrics" ADD COLUMN "acquisition_metrics" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "acquisition_funnel_benchmarks" ADD CONSTRAINT "acquisition_funnel_benchmarks_funnel_key_acquisition_funnels_funnel_key_fk" FOREIGN KEY ("funnel_key") REFERENCES "public"."acquisition_funnels"("funnel_key") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "acquisition_funnel_benchmarks_scope_idx" ON "acquisition_funnel_benchmarks" USING btree ("funnel_key","benchmark_key","sector");
--> statement-breakpoint
INSERT INTO "acquisition_funnels" ("funnel_key", "label", "description", "steps") VALUES
('lead_magnet', 'Lead magnet', 'Ils téléchargent un PDF ou suivent une formation gratuite.', $$[{"order":1,"metricKey":"audience","inputMetricKey":"content_views","label":"Audience","unit":"vues","benchmarkKey":null},{"order":2,"metricKey":"lead_magnet_clicks","inputMetricKey":"content_clicks","label":"Clics lead magnet","unit":"clics","benchmarkKey":"lead_magnet_click_rate"},{"order":3,"metricKey":"lead_magnet_leads","inputMetricKey":"content_leads","label":"Leads (opt-in)","unit":"leads","benchmarkKey":"lead_magnet_optin_rate"},{"order":4,"metricKey":"booked_calls","inputMetricKey":"calls_booked","label":"RDV réservés","unit":"RDV","benchmarkKey":"lead_magnet_booking_rate"},{"order":5,"metricKey":"attended_calls","inputMetricKey":"calls_attended","label":"RDV honorés","unit":"RDV","benchmarkKey":"lead_magnet_show_up_rate"},{"order":6,"metricKey":"sales_closed","inputMetricKey":"sales_closed","label":"Ventes","unit":"ventes","benchmarkKey":"lead_magnet_closing_rate"}]$$::jsonb),
('vsl', 'VSL', 'Ils regardent une vidéo de vente puis réservent.', $$[{"order":1,"metricKey":"audience","inputMetricKey":"content_views","label":"Audience","unit":"vues","benchmarkKey":null},{"order":2,"metricKey":"vsl_clicks","inputMetricKey":"content_clicks","label":"Clics VSL","unit":"clics","benchmarkKey":"vsl_click_rate"},{"order":3,"metricKey":"vsl_views","inputMetricKey":"vsl_views","label":"Vues VSL","unit":"spectateurs","benchmarkKey":"vsl_view_rate"},{"order":4,"metricKey":"booked_calls","inputMetricKey":"calls_booked","label":"RDV réservés","unit":"RDV","benchmarkKey":"vsl_booking_rate"},{"order":5,"metricKey":"attended_calls","inputMetricKey":"calls_attended","label":"RDV honorés","unit":"RDV","benchmarkKey":"vsl_show_up_rate"},{"order":6,"metricKey":"sales_closed","inputMetricKey":"sales_closed","label":"Ventes","unit":"ventes","benchmarkKey":"vsl_closing_rate"}]$$::jsonb),
('quiz', 'Quiz', 'Ils font un test et reçoivent un résultat.', $$[{"order":1,"metricKey":"audience","inputMetricKey":"content_views","label":"Audience","unit":"vues","benchmarkKey":null},{"order":2,"metricKey":"quiz_clicks","inputMetricKey":"quiz_clicks","label":"Clics quiz","unit":"clics","benchmarkKey":"quiz_click_rate"},{"order":3,"metricKey":"quiz_completed","inputMetricKey":"quiz_completed","label":"Quiz complétés","unit":"quiz","benchmarkKey":"quiz_completion_rate"},{"order":4,"metricKey":"booked_calls","inputMetricKey":"calls_booked","label":"RDV réservés","unit":"RDV","benchmarkKey":"quiz_booking_rate"},{"order":5,"metricKey":"attended_calls","inputMetricKey":"calls_attended","label":"RDV honorés","unit":"RDV","benchmarkKey":"quiz_show_up_rate"},{"order":6,"metricKey":"sales_closed","inputMetricKey":"sales_closed","label":"Ventes","unit":"ventes","benchmarkKey":"quiz_closing_rate"}]$$::jsonb),
('appel_direct', 'Appel direct', 'Ils réservent directement depuis ton contenu.', $$[{"order":1,"metricKey":"audience","inputMetricKey":"content_views","label":"Audience","unit":"vues","benchmarkKey":null},{"order":2,"metricKey":"booking_link_clicks","inputMetricKey":"booking_link_clicks","label":"Clics lien de réservation","unit":"clics","benchmarkKey":"direct_booking_link_rate"},{"order":3,"metricKey":"booked_calls","inputMetricKey":"calls_booked","label":"RDV réservés","unit":"RDV","benchmarkKey":"direct_booking_rate"},{"order":4,"metricKey":"attended_calls","inputMetricKey":"calls_attended","label":"RDV honorés","unit":"RDV","benchmarkKey":"direct_show_up_rate"},{"order":5,"metricKey":"sales_closed","inputMetricKey":"sales_closed","label":"Ventes","unit":"ventes","benchmarkKey":"direct_closing_rate"}]$$::jsonb),
('setting_dm', 'DM', 'Tu leur écris ou ils répondent à tes stories.', $$[{"order":1,"metricKey":"new_followers","inputMetricKey":"new_followers","label":"Nouveaux abonnés","unit":"abonnés","benchmarkKey":null},{"order":2,"metricKey":"first_messages","inputMetricKey":"first_messages","label":"1ers messages","unit":"messages","benchmarkKey":"setting_response_rate"},{"order":3,"metricKey":"conversations","inputMetricKey":"conversations","label":"Conversations","unit":"conversations","benchmarkKey":"setting_proposal_rate"},{"order":4,"metricKey":"calls_proposed","inputMetricKey":"calls_proposed","label":"Appels proposés","unit":"appels","benchmarkKey":"setting_booking_rate"},{"order":5,"metricKey":"calls_booked","inputMetricKey":"calls_booked","label":"RDV réservés","unit":"RDV","benchmarkKey":"setting_show_up_rate"},{"order":6,"metricKey":"calls_attended","inputMetricKey":"calls_attended","label":"RDV honorés","unit":"RDV","benchmarkKey":"setting_closing_rate"},{"order":7,"metricKey":"sales_closed","inputMetricKey":"sales_closed","label":"Ventes","unit":"ventes","benchmarkKey":"setting_sales_rate"}]$$::jsonb),
('webinaire', 'Webinaire', 'Ils s’inscrivent à un événement puis passent à l’action.', $$[{"order":1,"metricKey":"audience","inputMetricKey":"content_views","label":"Audience","unit":"vues","benchmarkKey":null},{"order":2,"metricKey":"webinar_registrants","inputMetricKey":"webinar_registrants","label":"Inscrits","unit":"inscrits","benchmarkKey":"webinar_registration_rate"},{"order":3,"metricKey":"webinar_attendees","inputMetricKey":"webinar_attendees","label":"Présents","unit":"présents","benchmarkKey":"webinar_attendance_rate"},{"order":4,"metricKey":"booked_calls","inputMetricKey":"calls_booked","label":"RDV réservés","unit":"RDV","benchmarkKey":"webinar_booking_rate"},{"order":5,"metricKey":"attended_calls","inputMetricKey":"calls_attended","label":"RDV honorés","unit":"RDV","benchmarkKey":"webinar_show_up_rate"},{"order":6,"metricKey":"sales_closed","inputMetricKey":"sales_closed","label":"Ventes","unit":"ventes","benchmarkKey":"webinar_closing_rate"}]$$::jsonb),
('challenge', 'Challenge', 'Ils s’inscrivent et participent à un challenge.', $$[{"order":1,"metricKey":"audience","inputMetricKey":"content_views","label":"Audience","unit":"vues","benchmarkKey":null},{"order":2,"metricKey":"challenge_registrants","inputMetricKey":"challenge_registrants","label":"Inscrits","unit":"inscrits","benchmarkKey":"challenge_registration_rate"},{"order":3,"metricKey":"challenge_active","inputMetricKey":"challenge_active","label":"Participants actifs","unit":"participants","benchmarkKey":"challenge_participation_rate"},{"order":4,"metricKey":"booked_calls","inputMetricKey":"calls_booked","label":"RDV réservés","unit":"RDV","benchmarkKey":"challenge_booking_rate"},{"order":5,"metricKey":"attended_calls","inputMetricKey":"calls_attended","label":"RDV honorés","unit":"RDV","benchmarkKey":"challenge_show_up_rate"},{"order":6,"metricKey":"sales_closed","inputMetricKey":"sales_closed","label":"Ventes","unit":"ventes","benchmarkKey":"challenge_closing_rate"}]$$::jsonb),
('newsletter', 'Newsletter', 'Ils lisent tes emails et cliquent vers ton offre.', $$[{"order":1,"metricKey":"newsletter_subscribers","inputMetricKey":"newsletter_subscribers","label":"Abonnés","unit":"abonnés","benchmarkKey":null},{"order":2,"metricKey":"newsletter_opens","inputMetricKey":"newsletter_opens","label":"Ouvertures","unit":"ouvertures","benchmarkKey":"newsletter_open_rate"},{"order":3,"metricKey":"newsletter_offer_clicks","inputMetricKey":"newsletter_offer_clicks","label":"Clics offre","unit":"clics","benchmarkKey":"newsletter_click_rate"},{"order":4,"metricKey":"booked_calls","inputMetricKey":"calls_booked","label":"RDV réservés","unit":"RDV","benchmarkKey":"newsletter_booking_rate"},{"order":5,"metricKey":"attended_calls","inputMetricKey":"calls_attended","label":"RDV honorés","unit":"RDV","benchmarkKey":"newsletter_show_up_rate"},{"order":6,"metricKey":"sales_closed","inputMetricKey":"sales_closed","label":"Ventes","unit":"ventes","benchmarkKey":"newsletter_closing_rate"}]$$::jsonb),
('vente_directe', 'Vente directe', 'Ils arrivent sur ta page de vente et achètent directement.', $$[{"order":1,"metricKey":"audience","inputMetricKey":"content_views","label":"Audience","unit":"vues","benchmarkKey":null},{"order":2,"metricKey":"sales_page_visitors","inputMetricKey":"sales_page_visitors","label":"Visiteurs page de vente","unit":"visiteurs","benchmarkKey":"direct_sales_page_rate"},{"order":3,"metricKey":"checkouts_started","inputMetricKey":"checkouts_started","label":"Checkouts initiés","unit":"checkouts","benchmarkKey":"direct_checkout_rate"},{"order":4,"metricKey":"sales_closed","inputMetricKey":"sales_closed","label":"Ventes","unit":"ventes","benchmarkKey":"direct_purchase_rate"}]$$::jsonb),
('communaute', 'Communauté', 'Ils rejoignent ta communauté puis deviennent actifs.', $$[{"order":1,"metricKey":"audience","inputMetricKey":"content_views","label":"Audience","unit":"vues","benchmarkKey":null},{"order":2,"metricKey":"community_joined","inputMetricKey":"community_joined","label":"Membres rejoints","unit":"membres","benchmarkKey":"community_join_rate"},{"order":3,"metricKey":"community_active","inputMetricKey":"community_active","label":"Membres actifs","unit":"membres","benchmarkKey":"community_active_rate"},{"order":4,"metricKey":"booked_calls","inputMetricKey":"calls_booked","label":"RDV réservés","unit":"RDV","benchmarkKey":"community_booking_rate"},{"order":5,"metricKey":"attended_calls","inputMetricKey":"calls_attended","label":"RDV honorés","unit":"RDV","benchmarkKey":"community_show_up_rate"},{"order":6,"metricKey":"sales_closed","inputMetricKey":"sales_closed","label":"Ventes","unit":"ventes","benchmarkKey":"community_closing_rate"}]$$::jsonb)
ON CONFLICT ("funnel_key") DO NOTHING;
--> statement-breakpoint
WITH seeds("funnel_key", "benchmarks") AS (VALUES
('lead_magnet', '{"lead_magnet_click_rate":0.25,"lead_magnet_optin_rate":0.2,"lead_magnet_booking_rate":0.35,"lead_magnet_show_up_rate":0.6,"lead_magnet_closing_rate":0.3}'::jsonb),
('vsl', '{"vsl_click_rate":0.35,"vsl_view_rate":0.5,"vsl_booking_rate":0.35,"vsl_show_up_rate":0.6,"vsl_closing_rate":0.3}'::jsonb),
('quiz', '{"quiz_click_rate":0.25,"quiz_completion_rate":0.5,"quiz_booking_rate":0.35,"quiz_show_up_rate":0.6,"quiz_closing_rate":0.3}'::jsonb),
('appel_direct', '{"direct_booking_link_rate":0.1,"direct_booking_rate":0.35,"direct_show_up_rate":0.6,"direct_closing_rate":0.3}'::jsonb),
('setting_dm', '{"setting_response_rate":0.35,"setting_proposal_rate":0.5,"setting_booking_rate":0.35,"setting_show_up_rate":0.6,"setting_closing_rate":0.3,"setting_sales_rate":0.3}'::jsonb),
('webinaire', '{"webinar_registration_rate":0.25,"webinar_attendance_rate":0.4,"webinar_booking_rate":0.35,"webinar_show_up_rate":0.6,"webinar_closing_rate":0.3}'::jsonb),
('challenge', '{"challenge_registration_rate":0.2,"challenge_participation_rate":0.5,"challenge_booking_rate":0.35,"challenge_show_up_rate":0.6,"challenge_closing_rate":0.3}'::jsonb),
('newsletter', '{"newsletter_open_rate":0.4,"newsletter_click_rate":0.05,"newsletter_booking_rate":0.35,"newsletter_show_up_rate":0.6,"newsletter_closing_rate":0.3}'::jsonb),
('vente_directe', '{"direct_sales_page_rate":0.3,"direct_checkout_rate":0.15,"direct_purchase_rate":0.3}'::jsonb),
('communaute', '{"community_join_rate":0.1,"community_active_rate":0.5,"community_booking_rate":0.35,"community_show_up_rate":0.6,"community_closing_rate":0.3}'::jsonb)
)
INSERT INTO "acquisition_funnel_benchmarks" ("funnel_key", "benchmark_key", "value")
SELECT seeds."funnel_key", benchmark_values.key, benchmark_values.value::real
FROM seeds CROSS JOIN LATERAL jsonb_each_text(seeds."benchmarks") AS benchmark_values(key, value)
ON CONFLICT DO NOTHING;
